"""
StayChat Hotel Assistant - Post-Generation Response Validator
Performs factual checks on generated answers to prevent pricing or URL hallucinations.
"""

import re
import logging
from typing import List, Dict, Any, Tuple

logger = logging.getLogger("StayChatResponseValidator")


class ResponseValidator:
    """
    Response Validation Engine.
    Deterministic audit layer checking for ungrounded numbers, URLs, and codes.
    """

    def __init__(self) -> None:
        # Regex to capture numeric entities representing prices (e.g. ₹4500, 7000)
        # We capture numbers of 3 to 5 digits representing currency or times
        self.price_pattern = re.compile(r"\b(\d{3,5})\b")
        # Regex to capture typical checkout URLs or links
        self.url_pattern = re.compile(r"\b(?:https?://|www\.)\S+\b", re.IGNORECASE)

    def _extract_prices(self, text: str) -> List[int]:
        """Extracts integers between 100 and 99999 from text (filtering small enumerators)."""
        numbers = self.price_pattern.findall(text)
        return [int(num) for num in numbers if 100 <= int(num) <= 99999]

    def _extract_urls(self, text: str) -> List[str]:
        """Extracts URL strings from text."""
        return self.url_pattern.findall(text)

    def validate(self, response: str, retrieved_contexts: List[str]) -> Dict[str, Any]:
        """
        Audits the generated response draft against the reference chunks.
        
        Args:
            response: The draft output generated by Gemini.
            retrieved_contexts: Gold-standard context snippets retrieved from FAISS.
            
        Returns:
            Dict: Contains 'status' ('approved' | 'blocked') and associated metadata.
        """
        logger.info("Executing post-generation factual entailment audit...")
        
        combined_context = "\n".join(retrieved_contexts)
        
        # 1. Audit Numerical Entities (Solves Room Pricing Hallucinations)
        gen_prices = self._extract_prices(response)
        context_prices = self._extract_prices(combined_context)
        
        for price in gen_prices:
            if price not in context_prices:
                reason = f"Numerical Hallucination Blocked: Response mentions unauthorized price '₹{price}' not in retrieved context."
                logger.warning(reason)
                return {
                    "status": "blocked",
                    "reason": "unsupported_claim",
                    "detail": reason
                }

        # 2. Audit URL Entities (Solves Phishing/Sensitive Leakage)
        gen_urls = self._extract_urls(response)
        context_urls = self._extract_urls(combined_context)
        
        for url in gen_urls:
            # We compare domain/url match
            if not any(url.lower() in ctx_url.lower() for ctx_url in context_urls):
                reason = f"Sensitive Link Blocked: Response contains unauthorized URL '{url}' not in retrieved context."
                logger.warning(reason)
                return {
                    "status": "blocked",
                    "reason": "unsupported_claim",
                    "detail": reason
                }

        # 3. Audit Reservation Codes / Alphanumeric booking patterns
        # Standard reservation code: e.g. RES-12345 or confirm codes
        ref_patterns = [r"\b[a-z]{3}-\d{4,6}\b", r"\bres-\d{4,6}\b"]
        for pattern in ref_patterns:
            gen_refs = re.findall(pattern, response.lower())
            context_refs = re.findall(pattern, combined_context.lower())
            for ref in gen_refs:
                if ref not in context_refs:
                    reason = f"Security Violation Blocked: Response references ungrounded booking reference '{ref}'."
                    logger.warning(reason)
                    return {
                        "status": "blocked",
                        "reason": "unsupported_claim",
                        "detail": reason
                    }

        logger.info("Post-generation audit successful. 0 ungrounded claims detected.")
        return {"status": "approved"}
